version: "2"

run:
  timeout: 5m

linters:
  default: none

  enable:
    - errcheck
    - staticcheck
    - govet
    - gosec
    - gocritic
    - unused

formatters:
  enable:
    - gofumpt
    - goimports

issues:
  max-same-issues: 0
  max-issues-per-linter: 0